name: trip_advisor_api
description: A dart package to communicate with trip advisor api. this package lets you do all of the api's functions
version: 1.0.6
# homepage: https://www.example.com
repository: https://github.com/Gypsy-IL/trip_advisor_api

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  http: ^0.13.5
  json_annotation: ^4.7.0
  json_serializable: ^6.5.2

dev_dependencies:
  build_runner: ^2.3.1
  lints: ^2.0.0
  test: ^1.16.0